app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    blogs = db.relationship('Blog',backref = 'user',lazy="dynamic")
    email = db.Column(db.String(255),unique = True,index = True)
    
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    @property
    def password(self):
            raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
            self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
            return check_password_hash(self.pass_secure,password)
   
    def __repr__(self):
        return f'User {self.username}'

    @login_manager.user_loader
    def load_user(user_id):
            return User.query.get(int(user_id))
   

class Blog(db.Model):
    __tablename__ = 'blogs'

    id = db.Column(db.Integer,primary_key = True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    description = db.Column(db.String(255))
    comments = db.relationship('Comment',backref = 'blog',lazy="dynamic")

    
    def save_blogs(self):
        db.session.add(self)
        db.session.commit()


    @classmethod
    def clear_blogs(cls):
        Blog.all_blogs.clear()

    @classmethod
    def get_blogs(id):
        blogs=Blog.query.all()

        return blogs

   

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer,primary_key = True)
   
    blog_id = db.Column(db.Integer,db.ForeignKey('blogs.id'))
    comment = db.Column(db.String(255))

    def save_comments(self):
        db.session.add(self)
        db.session.commit()


    @classmethod
    def clear_blogs(cls):
        Blog.all_blogs.clear()
    

    @classmethod
    def get_comments(id):
        all_comments=Comment.query.all()

        return all_comments

    def delete_comment(self):
        db.session.delete(self)
        db.session.commit()    

class Subscribe(db.Model):
    __tablename__ = 'subsribes'

    id = db.Column(db.Integer,primary_key = True)
    email = db.Column(db.String(255))
    

    def __repr__(self):
        return f'User {self.username}'


class Quote:
    '''
    Quote class to define Quote Objects
    '''

    def __init__(self,author,id,quote):
        self.author=author
        self.id =id
        self.quote=quote
        

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class BlogForm(FlaskForm):

    
    description = TextAreaField('create blog', validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):

    comment= TextAreaField('make comments', validators=[Required()])
    submit = SubmitField('Submit')

class SubscriptionForm(FlaskForm):

    email= TextAreaField('Enter your Email', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


bootstrap = Bootstrap()
db = SQLAlchemy()
mail=Mail()
photos = UploadSet('photos',IMAGES)

def create_app(config_name):
    app = Flask(__name__)
   
    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    # configure UploadSet
    configure_uploads(app,photos)
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    # setting config
    from .request import configure_request
    configure_request(app)
    # configure UploadSet
    configure_uploads(app,photos)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    
    
    return app
   
 
   
     

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
 
from . import main
from .forms import BlogForm,UpdateProfile
# from .. import db

from .forms import BlogForm

from flask_login import login_required 

from flask import render_template,redirect,url_for, abort
from . import main

from .. import db,photos
from ..models import User,Blog,Comment,Subscribe
from .forms import BlogForm,CommentForm,SubscriptionForm

from ..request import get_quotes
from ..email import mail_message

@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    quotes = get_quotes()
    
    all_blogs = Blog.get_blogs()
    
    title = 'Home - Welcome to The best blogs Website Online'

    return render_template('index.html', title = title ,all_blogs = all_blogs,quotes=quotes)


@main.route('/blog/new', methods = ['GET','POST'])
def new_blog():
    form = BlogForm()
    blogs =Blog.get_blogs()

    if form.validate_on_submit():
       
        description = form.description.data
        new_blog = Blog(description=description)
        new_blog.save_blogs()
        return redirect(url_for('main.index',description=description))
        

    title = 'Welcome to The best blogs Website Online'
    return render_template('blog.html',title = title, Blog_form=form,blogs=blogs)


@main.route('/blogs')
def dipslay_blogs():
   all_blogs = Blog.blogs()
   print(all_blogs)
   return render_template("index.html",all_blogs=all_blogs) 

@main.route('/blog/new', methods = ['GET','POST'])
@login_required
def create_blog():
   form = BlogForm()
   Blog = blog.Blog


   if form.validate_on_submit():
       
       teaser = form.teaser.data
       blog = form.blog.data
       new_blog = Blog(user_id=current_user.id,teaser=teaser, blog=blog)
       new_blog.save_new()
       return redirect(url_for('.index',blog = blog))

   
   return render_template('blog.html', blog_form=form)


@main.route('/blogs')
def display_blog():
   all_blogs = Blog.get_blogs()
   print(all_blogs)
   return render_template("index.html",all_blogs=all_blogs)

@main.route('/comment/delete/<int:id>')

def delete_comment(id):

  
  comment=Comment.query.filter_by(id=id).all()
  if comment is not None:
      comment.delete_comment()

  db.session.add(comment)
  db.session.commit()    

  
  return redirect('.main.index')   


@main.route('/comment/new/<int:id>', methods = ['GET','POST'])
def new_comment(id):
    form = CommentForm()
    comment = form.comment.data
    
    if form.validate_on_submit():
        new_comment = Comment(blog_id =id ,comment=comment)
        new_comment.save_comments()
        return redirect(url_for('main.index'))
    
    comments=Comment.query.filter_by(blog_id=id).all()

    title = 'Welcome to The best blogs Website Online'
    return render_template('comment.html',comments=comments,comment_form=form)


@main.route('/comments')
def dipslay_comments():
  
   all_comments = Comment. get_comments()
   print(all_comments)
   return render_template("comment.html",all_comments=all_comments) 



@main.route('/subscribe', methods = ['GET','POST'])
def new_subscription():
    form = SubscriptionForm()
    email= form.email.data
    

    if form.validate_on_submit():
        new_subscription = Subscribe(email=email)
        db.session.add(new_subscription)
        db.session.commit()
        mail_message("Welcome to quote and blogs","email/welcome_user",new_subscription.email,new_subscription=new_subscription)
       

        return redirect(url_for('main.index'))
   
    return render_template('subscription.html',form=form)






@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to the best blog Review website </title>
        {% endif %} 
        {% extends 'bootstrap/base.html'%}

        <!-- Navbar block  --> 
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock %}
    </head>
    <body>
        <!-- Content block -->

        {% block content %}

        {% endblock%}
    </body>
</html>

app/templates/blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}



<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to the best blogs website </title>
        {% endif %}
        

<!-- Styles block -->

        {% block styles%}
        {{ super() }}
        <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
        {% endblock %}
        
    </head>
  

{% block content %}
    <div class="container">

        <div class="col-md-8">

           
        </div>

        <div class="col-md-4">

            {{ wtf.quick_form(Blog_form) }}
        </div>
        
    </div>

{% endblock %}

app/templates/comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}



<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to the best blogs  website </title>
        {% endif %}
        

<!-- Styles block -->

        {% block styles%}
        {{ super() }}
        <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
        {% endblock %}
        
    </head>
{% block content %}
 <div class="container">

  <div>

    {{ wtf.quick_form(comment_form) }}
   </div>
    
   <div class="well-lg">
     {%for word in comments%}
     <p>{{word.comment}}</p>
     <button><a href="/comment/delete/">Delete comment</a></button>
     {%endfor%}
     
 </div>
{% endblock%}

app/templates/fourohfour.html
<p>oooops! sorry</p>

app/templates/index.html
 
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to the best all_blogs  website </title>
        {% endif %}
        {% extends 'base.html'%}
       
<!-- Styles block -->

        {% block styles%}
        {{ super() }}
        <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
        {% endblock %}
        
    </head>
  
 <body>

 

    {% block content %}
    <div class="container">
    <h1>Here is good blogs and Quotes</h1>
        
    {% for blog in all_blogs %}

    <p>{{blog.description}}</p>
    <button  class="button"><a href="/comment/new/{{blog.id}}">comment</a></button> 
    <button class="button"><a href="/comment/new/{{blog.id}}">view comment</a></button> 
    {% endfor %}

     <!-- quotes section  -->
     
     <ul>
       
     <li>{{ quotes.author}}</li>
     <li>{{ quotes.quote}}</li>
       
    </ul>
   
    <div class="well-lg">
        {%for word in all_comments%}
        <p>{{word.comment}}</p>
        {%endfor%}
    </div>




    <button><a href="/subscribe" >Subscribe here</a></button>
    </div>
    {% endblock%}
    
</body>
</html>

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
           
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
            <ul class="nav navbar-nav" style="margin:0%">
                    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            </ul>
            <ul class="nav navbar-nav" style="margin:0%">
                    {% if current_user.is_authenticated %}
                    
                    <li>
                    {% else %}
                    <li><a href="{{url_for('auth.login')}}">Sign in</a></li>

                    
                    {%endif%}
            </ul>
          
                
           
    

    </div>

    </div>
</div>



  

app/templates/new_blog.html
{% extends 'base.html'%}

{% block content %}

<div class="container">

   {%for blog in all_blogs%}
   {{blog}}
{{endfor}}
</div>

   
{% endblock%}
       
</body>
</html>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>

  {% if user == current_user %}
  <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

    <input type="file"  name="photo" class="form-control" required>
    <input type="submit">
  </form>
    {% endif %}
</div>


</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/subscription.html
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}


<div class="container">
<div>
  

{{ wtf.quick_form(form) }}
   
</div>
</div>

{% endblock%}